/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  theme: {
    extend: {
      colors: {
        'cat-ai':       'var(--color-ai)',
        'cat-security': 'var(--color-security)',
        'cat-finance':  'var(--color-finance)',
        'cat-startup':  'var(--color-startup)',
        'cat-bid':      'var(--color-bid)',
        'cat-general':  'var(--color-general)',
        'success': 'var(--color-success)',
        'warning': 'var(--color-warning)',
        'error':   'var(--color-error)',
        'info':    'var(--color-info)',
        'dark-bg':      'var(--bg-primary)',
        'dark-card':    'var(--bg-card)',
        'dark-hover':   'var(--bg-hover)',
        'dark-elevated':'var(--bg-elevated)',
        'dark-border':  'var(--border-color)',
        'accent-cyan':   'var(--color-ai)',
        'accent-red':    'var(--color-security)',
        'accent-gold':   'var(--color-finance)',
        'accent-purple': 'var(--color-startup)',
        'accent-orange': 'var(--color-bid)',
        'accent-green':  'var(--color-general)',
        'text-main':       'var(--text-primary)',
        'text-secondary':  'var(--text-secondary)',
        'text-muted':      'var(--text-muted)',
      },
      fontFamily: {
        'sans': [
          'Inter',
          'system-ui',
          '-apple-system',
          'Segoe UI',
          'PingFang SC',
          'Hiragino Sans GB',
          'Microsoft YaHei',
          'Noto Sans SC',
          'WenQuanYi Micro Hei',
          'sans-serif',
        ],
        'mono': [
          'JetBrains Mono',
          'Fira Code',
          'Cascadia Code',
          'monospace',
        ],
        'serif': ['Newsreader', 'Iowan Old Style', 'Apple Garamond', 'serif'],
      },
      fontWeight: {
        normal:  '400',
        medium:  '500',
        semibold:'600',
        bold:    '700',
      },
      letterSpacing: {
        tightest: '-0.02em',
        tight:    '-0.01em',
        normal:   '0',
        wide:     '0.04em',
        wider:    '0.08em',
      },
      lineHeight: {
        tight:   '1.2',
        snug:    '1.4',
        normal:  '1.5',
        relaxed: '1.6',
      },
      fontSize: {
        'xs':   ['11px', { lineHeight: '1.5' }],
        'sm':   ['13px', { lineHeight: '1.5' }],
        'base': ['14px', { lineHeight: '1.6' }],
        'lg':   ['16px', { lineHeight: '1.4' }],
        'xl':   ['20px', { lineHeight: '1.3' }],
      },
      borderRadius: {
        'sm':   'var(--radius-sm)',
        'md':   'var(--radius-md)',
        'lg':   'var(--radius-lg)',
        'xl':   'var(--radius-xl)',
        'full': 'var(--radius-full)',
      },
      boxShadow: {
        'card':     'var(--shadow-card)',
        'elevated': 'var(--shadow-elevated)',
        'popover':  'var(--shadow-popover)',
        'modal':    'var(--shadow-modal)',
        'toast':    'var(--shadow-toast)',
        'glow':     'var(--shadow-glow)',
      },
      spacing: {
        '0':  'var(--space-0)',
        '1':  'var(--space-1)',
        '2':  'var(--space-2)',
        '3':  'var(--space-3)',
        '4':  'var(--space-4)',
        '5':  'var(--space-5)',
        '6':  'var(--space-6)',
        '7':  'var(--space-7)',
        '8':  'var(--space-8)',
      },
      zIndex: {
        'base':     'var(--z-base)',
        'dropdown': 'var(--z-dropdown)',
        'sticky':   'var(--z-sticky)',
        'overlay':  'var(--z-overlay)',
        'modal':    'var(--z-modal)',
        'popover':  'var(--z-popover)',
        'toast':    'var(--z-toast)',
        'tooltip':  'var(--z-tooltip)',
      },
      transitionDuration: {
        'fast':   'var(--duration-fast)',
        'normal': 'var(--duration-normal)',
        'slow':   'var(--duration-slow)',
      },
      transitionTimingFunction: {
        'out':    'var(--ease-out)',
        'in-out': 'var(--ease-in-out)',
        'spring': 'var(--ease-spring)',
      },
    },
  },
  plugins: [],
}